config/routes.rb
Rails.application.routes.draw do




  resources :room_tutor_msgs
  resources :room_tutors
  resources :room_msgs
  resources :rooms

  resources :improvements

  resources :submissions
  resources :quizzes, only: [:index, :new, :create, :destroy]
  devise_for :admins
  devise_for :tutors, path: 'tutors', controllers: { registrations: "tutors/registrations", sessions: "tutors/sessions"}
  devise_for :students, path: 'students', controllers: { registrations: "students/registrations", sessions: "students/sessions"}

  authenticated :tutor do
    root 'tutors/dashboards#home', as: :authenticated_tutor_root
    get 'profile', to: 'tutors/dashboards#profile', as: :authenticated_tutor_profile
    get 'quiz', to: 'tutors/quizzes#show'

    get 'setLocation', to: 'tutors/dashboards#setLocation'
    post 'setLocation', to: 'tutors/dashboards#setLocationSubmit'
    get 'setInfo', to: 'tutors/dashboards#setInfo'
    post 'setInfo', to: 'tutors/dashboards#updateInfo'
    post 'acceptStudent', to: 'tutors/dashboards#acceptStudent'
    post 'rejectStudent', to: 'tutors/dashboards#rejectStudent'
    post 'messages', to: 'tutors/dashboards#messages'

    get 'tutortest', to: 'tutors/quizzes#tutortest', as: :tutor_sign_up_test
    get 'tutortest/english', to: 'tutors/quizzes#english', as: :tutor_english_test
    get 'tutortest/spanish', to: 'tutors/quizzes#spanish', as: :tutor_spanish_test
    get 'tutortest/german', to: 'tutors/quizzes#german', as: :tutor_german_test
    get 'tutortest/french', to: 'tutors/quizzes#french', as: :tutor_french_test
    get 'tutortest/success', to: 'tutors/quizzes#success', as: :tutor_success

  end

  authenticated :student do
    root 'students/dashboards#home', as: :authenticated_student_root
    get 'profile', to: 'students/dashboards#profile', as: :authenticated_student_profile
    post 'rateTutor', to: 'students/dashboards#rateTutor'
    post 'pickLanguage', to: 'students/dashboards#pickLanguage'
    post 'requestTutor', to: 'students/dashboards#requestTutor'
    get 'findTutor', to: 'students/dashboards#maps'
    get 'flag', to: 'students/dashboards#flag'
    post 'flag', to: 'students/dashboards#sendFlag'
    get 'quizzes', to: 'quizzes#index'
  end

  authenticated :admin do
    get 'home', to: 'home#admins', as: :admin_home
    post "warnUser", to: 'home#warnUser'
    post "banUser", to: 'home#banUser'
    get 'ratings', to: 'home#ratings'
    get 'reports', to: 'home#reports'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Home page is the root
  root 'home#home'

end

app/models/tutor.rb
class Tutor < ApplicationRecord
  enum approval: [:unapproved, :approved]
  after_initialize :set_default_approval, :if => :new_record?
    def set_default_approval
      self.approval ||= :approved
    end

  mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
#don't delete student if tutor deletes account - but let them pick another tutor
has_many :students
has_many :meetings
validates :email, :forename, :surname, presence: true
validates :location, format: {with: /\((-{0,1})\d+(.{0,1})\d+,\s(-{0,1})\d+(.{0,1})\d+\)/, message: "invalid location format: #{:location}"}
end

app/controllers/students/dashboards_controller.rb
class Students::DashboardsController < ApplicationController
  include Accessible_student

  def home
    if current_student
      @language = current_student.language
      @tutor = Tutor.find(current_student.tutor_id)
      @tutor_rating = @tutor.rating
      @student = current_student
      @forename = @tutor.forename
      @surname = @tutor.surname
      @tutor_confirmed = current_student.tutor_confirmed
      @rated = current_student.rated
      @current_rating = current_student.current_rating
    end

  rescue ActiveRecord::RecordNotFound
    #in case the tutor has deleted their account
    current_student.tutor_id = nil
    current_student.tutor_confirmed = false
    current_student.save
  end

  def profile
  end

  def pickLanguage
    lang = params[:lang]
    current_student.language = lang
    current_student.save
    redirect_to authenticated_student_root_url
  end

  def requestTutor
    tutor_id = params[:tutor_id]
    current_student.tutor_id = tutor_id
    current_student.tutor_confirmed = false
    current_student.save!
    redirect_to authenticated_student_root_url
  end

  def rateTutor
    tutor = Tutor.find(current_student.tutor_id)
    rating = params[:tutor_rating].to_i
    current_rating_tutor = tutor.rating.to_f
    old_rating = current_student.current_rating
    num_rates = tutor.num_rates.to_i
    if current_student.rated?
      new_rating = (current_rating_tutor * num_rates)
      new_rating =  new_rating - old_rating
      new_rating =  new_rating + rating
      new_rating =  new_rating/(num_rates)
      tutor.rating = new_rating
      tutor.num_rates = num_rates
      current_student.current_rating = rating
      current_student.save!
    else
      new_rating = (current_rating_tutor + rating)/(num_rates+1)
      tutor.rating = new_rating
      tutor.num_rates = num_rates + 1
      current_student.current_rating = rating
      current_student.rated = true
      current_student.save!
    end
    tutor.save!
    redirect_to authenticated_student_root_url
  end

  def flag
    @tutor = Tutor.find(current_student.tutor_id)
  end

  def sendFlag
    #the student is reporting their tutor; save the tutor's id and their tutor status
    user_id = current_student.tutor_id
    user_type = 'tutor'
    reason = params[:flag_reason]
    description = params[:flag_desc]
    #save the params as a new report
    report = Report.new
    report.user_id = user_id
    report.user_type = user_type
    report.reason = reason
    report.description = description
    report.save!
    #deallocate student from their tutor
    current_student.tutor_id = nil
    current_student.tutor_confirmed = false
    #wipe the ratings, so it doesn't look like they've already rated a new tutor
    current_student.rated = false
    current_student.current_rating = 0
    current_student.save!
    @student = current_student
    redirect_to authenticated_student_root_url, notice: "Thank you for your report. You have been deregistered from your tutor and the admins will investigate them."
  end
end

app/controllers/tutors/confirmations_controller.rb
# frozen_string_literal: true

class Tutors::ConfirmationsController < Devise::ConfirmationsController
  include Accessible_tutor
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/tutors/dashboards_controller.rb
class Tutors::DashboardsController < ApplicationController
  include Accessible_tutor
  before_action :authenticate_tutor!
  before_action :check_approval

  def home
    if current_tutor
      @language = current_tutor.language
      @location = current_tutor.location
      @forename = current_tutor.forename
      @surname = current_tutor.surname
      @description = current_tutor.description
    end
  end

  def profile
  end

  def setLocationSubmit
    location = params[:location]
    current_tutor.location = location
    current_tutor.save
    redirect_to authenticated_tutor_root_url
  end

  def setInfo
    @language = current_tutor.language
    @forename = current_tutor.forename
    @surname = current_tutor.surname
    @description = current_tutor.description
  end

  def updateInfo
    if current_tutor
    @language = current_tutor.language
    @forename = current_tutor.forename
    @surname = current_tutor.surname
    @description = current_tutor.description
    forename = params[:forename]
    surname = params[:surname]
    language = params[:language]
    description = params[:description]
    current_tutor.forename = forename
    current_tutor.surname = surname
    current_tutor.language = language
    current_tutor.description = description
    current_tutor.save
    redirect_to authenticated_tutor_root_url
    end
  end

  def acceptStudent
    student_id = params[:student_id]
    @student = Student.find(student_id)
    @student.tutor_confirmed = true
    @student.save
    redirect_to authenticated_tutor_root_url
  end

  def rejectStudent
    student_id = params[:student_id]
    @student = Student.find(student_id)
    @student.tutor_id = nil
    @student.save
    redirect_to authenticated_tutor_root_url
  end

  def messages
  end

  private

  def check_approval
    if current_tutor.unapproved?
      flash[:notice] = "Pass the test to become an approved tutor"
      redirect_to(tutor_sign_up_test_path)
    end
  end

end

app/controllers/tutors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Tutors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Accessible_tutor
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/tutors/passwords_controller.rb
# frozen_string_literal: true

class Tutors::PasswordsController < Devise::PasswordsController
  include Accessible_tutor
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/tutors/quizzes_controller.rb
class Tutors::QuizzesController < ApplicationController
  include Accessible_tutor
  before_action :authenticate_tutor!

  def tutortest
  end

  def english
  end

  def spanish
  end

  def german
  end

  def french
  end

  def success
    current_tutor.approved!
    redirect_to authenticated_tutor_root_path
  end

end

app/controllers/tutors/registrations_controller.rb
# frozen_string_literal: true

class Tutors::RegistrationsController < Devise::RegistrationsController
  include Accessible_tutor
  skip_before_action :check_tutor, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
   devise_parameter_sanitizer.permit(:account_update, keys: [:forename, :surname, :dob, :phone, :description, :image, :job, :address, :country, :description2, :language])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    tutor_sign_up_test_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super(resource)
  # end

  # The path used after edit.
  def after_update_path_for(resource)
    authenticated_student_profile_path(resource)
  end
end

app/controllers/tutors/sessions_controller.rb
# frozen_string_literal: true

class Tutors::SessionsController < Devise::SessionsController
  include Accessible_tutor
  skip_before_action :check_tutor, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
      if resource.banned?
        sign_out resource
        flash[:error] = "This account has been banned for: " + resource.flag_reason.to_s + ". You are unable to access the account."
        root_path
      elsif resource.warned?
        flash[:error] = "This account has been warned for: " + resource.flag_reason.to_s+ ". If you receive another warning, you will be banned."
        sign_in resource
        super
      else
        super
      end
     end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/tutors/unlocks_controller.rb
# frozen_string_literal: true

class Tutors::UnlocksController < Devise::UnlocksController
  include Accessible_tutor
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/tutors/dashboards/home.html.erb
<h1><%= t('.welcome') %></h1>

<div class="tutoring">
  <h2><%= t('.your_tutees') %></h2>
  <% if ((@forename == ("First Name") || @surname == "Surname") || @description == nil )%>
  <%= puts("Forename #{@forename} surname #{@surname} description #{@description}")%>
    <h5> <%= t('.complete') %> </h5>
    <button type="button" name="button" class = "btn"><a href="setInfo">Complete my Profile</a></button>
  <% elsif @location != "(0.0, 0.0)"%>
    <%= puts("Forename #{@forename} surname #{@surname} description #{@description}")%>
  <h5> <%= t('.requests') %></h5>
    <%= puts("tutor #{current_tutor.id}")%>
    <ul>
   <% @students = Student.where(tutor_id: current_tutor.id, tutor_confirmed: false)
      @students.each do |student| %>

   <li><h6><%= student["forename"] %> &nbsp; <%= student["surname"] %>
     <%=button_to "Accept", {action: "acceptStudent", params: {:student_id => student["id"]}}, {class: 'btn'} %>
   <%=button_to "Reject", {action: "rejectStudent", params: {:student_id => student["id"]}}, {class: 'btn'} %></h6></li>
 <%  end %>
 </ul>
 <h5><%= t('.confirmed') %></h5>
 <ul>
 <% @students = Student.where(tutor_id: current_tutor.id, tutor_confirmed: true)
    @students.each do |student| %>
 <li><h6><%= student["forename"] %> &nbsp; <%= student["surname"] %>
   <%=button_to "Contact", {action: "messages", params: {:student_id => student["id"]}}, {class: 'btn'} %>
 </h6></li>
<%  end %>
</ul>

  <% else %>
      <p>Set a location so you can start tutoring.</p>
      <p></p>
      <button type="button" name="button" class = "btn"><a href="setLocation">Set my Location</a></button>
  <% end %>
</div>

<div>
  <h2> <%= t('.quiz_submissions') %> </h2>
  <button class = "btn"><a href="submissions"><%= t('.button_submissions') %></a></button>

</div>

<div>
  <h2> <%= t('.request_submissions') %> </h2>
  <button class = "btn"><a href="improvements"><%= t('.button_request') %></a></button>

</div>

<div>
  <h2> Live chat with other tutors</h2>
  <button class = "btn"><a href="room_tutors">Go to Chat Rooms</a></button>

</div>

app/views/tutors/dashboards/messages.html.erb
<h1>Placeholder for the messaging system</h1>

app/views/tutors/dashboards/profile.html.erb
<!DOCTYPE html>
<html>
<title>Edit your Profile</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <link rel="stylesheet" href="https://www.profileschools.com/profilecss/4/profile.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
<button class = "btn edit-profile"><%= link_to "Edit profile", :edit_tutor_registration, style: "color:orange" %></button>
<!-- Page Container -->
<div class="profile-content profile-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="profile-row-padding">

    <!-- Left Column -->
    <div class="profile-third">

      <div class="profile-white profile-text-orange profile-card-4">
        <div class="profile-display-container">
          <%= image_tag(current_tutor.image_url, style: "max-width:100%; max-height:100%") %>
          <div class="profile-display-bottomleft profile-container profile-text-black">
            <h2> <%= current_tutor.forename + " " + current_tutor.surname %> </h2>
          </div>
        </div>
        <hr>
        <div class="profile-display-container">
          <p><i class="fa fa-briefcase fa-fw profile-margin-right profile-large profile-text-orange"></i><%= current_tutor.job %></p>
          <p><i class="fa fa-home fa-fw profile-margin-right profile-large profile-text-orange"></i><%= current_tutor.address + " " + current_tutor.country %></p>
          <p><i class="fa fa-envelope fa-fw profile-margin-right profile-large profile-text-orange"></i> <%= current_tutor.email %> </p>
          <p><i class="fa fa-phone fa-fw profile-margin-right profile-large profile-text-orange"></i> <%= current_tutor.phone %> </p>
          <br/>
          <div class="profile-display-bottomleft profile-container edit-profile">
          </div>
        </div>
        <hr>
        <div class="profile-container">
          <!-- Accordion -->
          <div class="profile-card profile-round">
            <div class="profile-white">
              <button onclick="myFunction('Demo1')" class="profile-button profile-block profile-theme-l1 profile-left-align"><i class="fa fa-circle-o-notch fa-fw profile-margin-right"></i> <%= t('.my_tutees') %></button>
              <div id="Demo1" class="profile-hide profile-container">
                <p> <%= t('.list') %></p>
                <% @students = Student.where(tutor_id: current_tutor.id, tutor_confirmed: true)
                   @students.each do |student| %>
                <li><h6>
                  <%= student["forename"] %> &nbsp; <%= student["surname"] %>
                  <%=button_to "Contact", {action: "messages", params: {:student_id => student["id"]}}, {class: 'btn'} %>
                </h6></li>
               <%  end %>
              </div>
              <button onclick="myFunction('Demo2')" class="profile-button profile-block profile-theme-l1 profile-left-align"><i class="fa fa-calendar-check-o fa-fw profile-margin-right"></i> <%= t('.my_events') %> </button>
              <div id="Demo2" class="profile-hide profile-container">
                <p>Some text..</p>
              </div>
              <button onclick="myFunction('Demo3')" class="profile-button profile-block profile-theme-l1 profile-left-align"><i class="fa fa-users fa-fw profile-margin-right"></i> <%= t('.my_quizzes') %> </button>
              <div id="Demo3" class="profile-hide profile-container">
             <div class="profile-row-padding">
             <br>

               <div class="profile-half">
                 <%= link_to "New Quiz", new_quiz_path, class: "btn btn-primary" %>
               </div>
               <div class="profile-half">
                 <%= link_to "My Quizzes", quizzes_path, class: "btn btn-primary" %>
               </div>

             </div>
              </div>
            </div>
          </div>
        </div><br>
      </div><br>

    
      <ul>
      <div class="profile-card profile-round profile-white profile-center">
          <div class="profile-container">
            <p><%= t('.request') %></p>
     <% @students = Student.where(tutor_id: current_tutor.id, tutor_confirmed: false)
        @students.each do |student| %>

     <li><h6><%= student["forename"] %> &nbsp; <%= student["surname"] %></h6>
       <div class="profile-row profile-opacity">
         <div class="profile-half">
       <%=button_to "Accept", {action: "acceptStudent", params: {:student_id => student["id"]}}, {class: 'profile-button profile-block profile-green profile-section'} %>
       </div>
         <div class="profile-half">
     <%=button_to "Reject", {action: "rejectStudent", params: {:student_id => student["id"]}}, {class: 'profile-button profile-block profile-red profile-section'} %>
   </li>

 </div>
    <%  end %>
    <% if @students.length == 0%>
      <p><%= t('.message') %></p>
      <%end %>
    </ul>
      </div>
      <br>

    <!-- End Left Column -->


    <!-- Right Column -->
    <div class="profile-twothird">

      <div class="profile-container profile-card profile-white profile-margin-bottom">
        <h2 class="profile-text-orange profile-padding-16"><i class="fa fa-suitcase fa-fw profile-margin-right profile-xxlarge profile-text-orange"></i>About me</h2>
        <div class="profile-container">
          <h5 class="profile-opacity"><b><%= t('.description') %> </b></h5>
          <p> <%= current_tutor.description %> </p>
          <hr>
        </div>
        <div class="profile-container">
          <h5 class="profile-opacity"><b><%= t('.offer') %> </b></h5>
          <p> <%= current_tutor.description2 %> </p>
          <hr>
        </div>
        <div class="profile-container">
          <h5 class="profile-opacity"><b><%= t('.rating') %> </b></h5>
          <p>How people rate me </p>
          <hr>
        </div>
      </div>



    <!-- End Right Column -->
    </div>



  <!-- End Grid -->
  </div>

  <!-- End Page Container -->
</div>
<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("profile-show") == -1) {
    x.className += " profile-show";
    x.previousElementSibling.className += " profile-theme-d1";
  } else {
    x.className = x.className.replace("profile-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" profile-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("profile-show") == -1) {
    x.className += " profile-show";
  } else {
    x.className = x.className.replace(" profile-show", "");
  }
}
</script>
</body>
</html>

app/views/tutors/dashboards/schedule.html.erb
<html lang='en'>
  <head>
    <meta charset='utf-8' />

    <link href='calendar_main.css' rel='stylesheet' />
    <link href='calendar_daygrid.css' rel='stylesheet' />
    <link href='calendar_timegrid.css' rel='stylesheet' />


    <script src='calendar_main.js'></script>
    <script src='calendar_daygrid.js'></script>
    <script src='calendar_interaction.js'></script>
    <script src='calendar_timegrid.js'></script>

    <script>

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
          plugins: [ 'dayGrid', 'timeGrid', 'interaction' ],
          aspectRatio: 2,
          //contentHeight: 500,
          header: {
            left: 'dayGridMonth',
            center: 'title',
            right: 'prev, next'
          },
          events: '/meetings.json',
          eventColor: '#e88523',
        });

        calendar.render();
      });

    </script>
  </head>
  <body>

    <p>Create, View and edit your availabilities</p>
    <button type="button" name="button" class = "btn"><a href="meetings/new">Create Slot</a></button>
    <button type="button" name="button" class = "btn"><a href="meetings">Edit Slots</a></button>

    <div class="popup" onclick="releaseNotes()"><h3>Release Notes</h3>
      <span class="popuptext" id="myPopup">
        <p>Due to the ongoing Coronavirus Situation:</p>
        <p>The BeeSmart team has had to re-allocate resources to minimise delays, therefore the following features will be released in the next update:</p>
        <ol>
          <li>Addition of meetings to Google Calendar</li>
          <li>Weekly view of available meetings</li>
        </ol>

      </span>
    </div>

    <script>
      function releaseNotes() {
        var popup = document.getElementById("myPopup");
        popup.classList.toggle("show");
      }
    </script>


    <div id='calendar'></div>

  </body>
</html>

app/views/tutors/dashboards/setInfo.html.erb
<%= csrf_meta_tags %>
<h2>Finish your Profile</h2>

<%= form_tag('setInfo') %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div class="field">
    <%= label_tag :forename %><br />
    <%= text_field_tag :forename, @forename%>
  </div>
  <div class="field">
    <%= label_tag :surname %><br />
    <%= text_field_tag :surname, @surname %>
  </div>
  <div class="field">
      <%= label_tag :language, "What language are you teaching?" %><br />
    <%= select_tag :language,  options_for_select([['French', 'French'], ['German', 'German'], ['Spanish', 'Spanish'], ['English', 'English']]) %>

  </div>
  <div class="field">
    <%= label_tag :description, "Write a little about yourself to help students get to know you." %><br />
    <%= text_area_tag :description, @description %>
  </div>


  <div class="actions">
    <%= submit_tag "Update" %>
  </div>

app/views/tutors/dashboards/work_in_progress.html.erb
<h2>This feature is currently under construction</h2><br>
<h4>Due to delays caused by the current situation,
  <br> the add-to Google Calendar isn't quite ready</h4>
<p>We have been focusing our efforts in delivering our core language learning aims,
  <br>and look forward to bringing this feature to you in the next update. <br>
   We greatly value your patience while we work through this together</p>
<p>- the BeeSmart team</p>
<%= link_to 'Back', meetings_path %>