config/routes.rb
Rails.application.routes.draw do




  resources :room_tutor_msgs
  resources :room_tutors
  resources :room_msgs
  resources :rooms

  resources :improvements

  resources :submissions
  resources :quizzes, only: [:index, :new, :create, :destroy]
  devise_for :admins
  devise_for :tutors, path: 'tutors', controllers: { registrations: "tutors/registrations", sessions: "tutors/sessions"}
  devise_for :students, path: 'students', controllers: { registrations: "students/registrations", sessions: "students/sessions"}

  authenticated :tutor do
    root 'tutors/dashboards#home', as: :authenticated_tutor_root
    get 'profile', to: 'tutors/dashboards#profile', as: :authenticated_tutor_profile
    get 'quiz', to: 'tutors/quizzes#show'

    get 'setLocation', to: 'tutors/dashboards#setLocation'
    post 'setLocation', to: 'tutors/dashboards#setLocationSubmit'
    get 'setInfo', to: 'tutors/dashboards#setInfo'
    post 'setInfo', to: 'tutors/dashboards#updateInfo'
    post 'acceptStudent', to: 'tutors/dashboards#acceptStudent'
    post 'rejectStudent', to: 'tutors/dashboards#rejectStudent'
    post 'messages', to: 'tutors/dashboards#messages'

    get 'tutortest', to: 'tutors/quizzes#tutortest', as: :tutor_sign_up_test
    get 'tutortest/english', to: 'tutors/quizzes#english', as: :tutor_english_test
    get 'tutortest/spanish', to: 'tutors/quizzes#spanish', as: :tutor_spanish_test
    get 'tutortest/german', to: 'tutors/quizzes#german', as: :tutor_german_test
    get 'tutortest/french', to: 'tutors/quizzes#french', as: :tutor_french_test
    get 'tutortest/success', to: 'tutors/quizzes#success', as: :tutor_success

  end

  authenticated :student do
    root 'students/dashboards#home', as: :authenticated_student_root
    get 'profile', to: 'students/dashboards#profile', as: :authenticated_student_profile
    post 'rateTutor', to: 'students/dashboards#rateTutor'
    post 'pickLanguage', to: 'students/dashboards#pickLanguage'
    post 'requestTutor', to: 'students/dashboards#requestTutor'
    get 'findTutor', to: 'students/dashboards#maps'
    get 'flag', to: 'students/dashboards#flag'
    post 'flag', to: 'students/dashboards#sendFlag'
    get 'quizzes', to: 'quizzes#index'
  end

  authenticated :admin do
    get 'home', to: 'home#admins', as: :admin_home
    post "warnUser", to: 'home#warnUser'
    post "banUser", to: 'home#banUser'
    get 'ratings', to: 'home#ratings'
    get 'reports', to: 'home#reports'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Home page is the root
  root 'home#home'

end

app/models/tutor.rb
class Tutor < ApplicationRecord
  enum approval: [:unapproved, :approved]
  after_initialize :set_default_approval, :if => :new_record?
    def set_default_approval
      self.approval ||= :approved
    end

  mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
#don't delete student if tutor deletes account - but let them pick another tutor
has_many :students
has_many :meetings
validates :email, :forename, :surname, presence: true
validates :location, format: {with: /\((-{0,1})\d+(.{0,1})\d+,\s(-{0,1})\d+(.{0,1})\d+\)/, message: "invalid location format: #{:location}"}
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_tutor!, only: [:show, :edit, :update, :destroy]


  def index
    if tutor_signed_in?
      @quizzes = Quiz.tutor_quizzes(current_tutor)
    else
      @quizzes = Quiz.all
    end
  end

  def new
    @quiz = Quiz.new
  end


  def create
      cparams = quiz_params
      cparams[:tutor_id] = current_tutor.id
      @quiz = Quiz.new(cparams)

      if @quiz.save
        redirect_to quizzes_path, notice: "The quiz #{@quiz.topic} has been uploaded."
      else
        render "new"

      end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to quizzes_path, notice:  "The quiz  #{@quiz.topic} has been deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit( :language, :topic, :level, :attachment, :tutor_id)
    end
  end

app/controllers/tutors/confirmations_controller.rb
# frozen_string_literal: true

class Tutors::ConfirmationsController < Devise::ConfirmationsController
  include Accessible_tutor
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/tutors/dashboards_controller.rb
class Tutors::DashboardsController < ApplicationController
  include Accessible_tutor
  before_action :authenticate_tutor!
  before_action :check_approval

  def home
    if current_tutor
      @language = current_tutor.language
      @location = current_tutor.location
      @forename = current_tutor.forename
      @surname = current_tutor.surname
      @description = current_tutor.description
    end
  end

  def profile
  end

  def setLocationSubmit
    location = params[:location]
    current_tutor.location = location
    current_tutor.save
    redirect_to authenticated_tutor_root_url
  end

  def setInfo
    @language = current_tutor.language
    @forename = current_tutor.forename
    @surname = current_tutor.surname
    @description = current_tutor.description
  end

  def updateInfo
    if current_tutor
    @language = current_tutor.language
    @forename = current_tutor.forename
    @surname = current_tutor.surname
    @description = current_tutor.description
    forename = params[:forename]
    surname = params[:surname]
    language = params[:language]
    description = params[:description]
    current_tutor.forename = forename
    current_tutor.surname = surname
    current_tutor.language = language
    current_tutor.description = description
    current_tutor.save
    redirect_to authenticated_tutor_root_url
    end
  end

  def acceptStudent
    student_id = params[:student_id]
    @student = Student.find(student_id)
    @student.tutor_confirmed = true
    @student.save
    redirect_to authenticated_tutor_root_url
  end

  def rejectStudent
    student_id = params[:student_id]
    @student = Student.find(student_id)
    @student.tutor_id = nil
    @student.save
    redirect_to authenticated_tutor_root_url
  end

  def messages
  end

  private

  def check_approval
    if current_tutor.unapproved?
      flash[:notice] = "Pass the test to become an approved tutor"
      redirect_to(tutor_sign_up_test_path)
    end
  end

end

app/controllers/tutors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Tutors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Accessible_tutor
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/tutors/passwords_controller.rb
# frozen_string_literal: true

class Tutors::PasswordsController < Devise::PasswordsController
  include Accessible_tutor
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/tutors/quizzes_controller.rb
class Tutors::QuizzesController < ApplicationController
  include Accessible_tutor
  before_action :authenticate_tutor!

  def tutortest
  end

  def english
  end

  def spanish
  end

  def german
  end

  def french
  end

  def success
    current_tutor.approved!
    redirect_to authenticated_tutor_root_path
  end

end

app/controllers/tutors/registrations_controller.rb
# frozen_string_literal: true

class Tutors::RegistrationsController < Devise::RegistrationsController
  include Accessible_tutor
  skip_before_action :check_tutor, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
   devise_parameter_sanitizer.permit(:account_update, keys: [:forename, :surname, :dob, :phone, :description, :image, :job, :address, :country, :description2, :language])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    tutor_sign_up_test_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super(resource)
  # end

  # The path used after edit.
  def after_update_path_for(resource)
    authenticated_student_profile_path(resource)
  end
end

app/controllers/tutors/sessions_controller.rb
# frozen_string_literal: true

class Tutors::SessionsController < Devise::SessionsController
  include Accessible_tutor
  skip_before_action :check_tutor, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
      if resource.banned?
        sign_out resource
        flash[:error] = "This account has been banned for: " + resource.flag_reason.to_s + ". You are unable to access the account."
        root_path
      elsif resource.warned?
        flash[:error] = "This account has been warned for: " + resource.flag_reason.to_s+ ". If you receive another warning, you will be banned."
        sign_in resource
        super
      else
        super
      end
     end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/tutors/unlocks_controller.rb
# frozen_string_literal: true

class Tutors::UnlocksController < Devise::UnlocksController
  include Accessible_tutor
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/tutors/quizzes/english.html.erb
<script>
	function check(){

		var question1 = document.quiz.question1.value;
		var question2 = document.quiz.question2.value;
		var question3 = document.quiz.question3.value;
		var correct = 0;

		if (question1 == "three" || "3") {
			correct++;
		}
		if (question2 == "2") {
			correct++;
		}
		if (question3 == "have, be or will") {
			correct++;
		}

		var messages = ["Great job!", "You need all 3 correct to become a tutor", "You need all 3 correct to become a tutor"];
		var score;


		if (correct == 0) {
			score = 2;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct > 0 && correct < 3) {
			score = 1;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct == 3) {
			score = 0;
			document.getElementById("start").style.visibility = "visible"
		}

		document.getElementById("after_submit").style.visibility = "visible";
  	document.getElementById("message").innerHTML = messages[score];
  	document.getElementById("number_correct").innerHTML = "You got " + correct + " correct.";
  }

</script>

<h2><%= t('.description') %> </h2>
<h2><%= t('.status') %> : <%= current_tutor.approval %></h2>

<div class="field">
<h1><%= t('.test') %> </h1>
<form id = "quiz" name = "quiz">


<p class = "questions">There are ________ main verb tenses in English </p>
<input id = "textbox" type = "text" name = "question1">

<p class = "questions">English has ________ ways of forming a tense from the verb alone</p>
<input type = "radio" id = "mc" name = "question2" value = "2"> 2<br>
<input type = "radio" id = "mc" name = "question2" value = "3"> 3<br>

<p class = "questions">To form other verb tenses, you have to add a form of _______ in front of the verb</p>

<input type = "radio" id = "mc" name = "question3" value = "have, be or will"> have, be or will<br>
<input type = "radio" id = "mc" name = "question3" value = "have"> have<br>


<input id = "button" type = "button" value = "I'm finished!" onclick = "check();">

</form>

<div id = "after_submit">
<p id = "number_correct"></p>
<p id = "message"></p>
<button id = "refresh", class ="btn"><%= link_to "Refresh", "" %></button>
<button id = "start", class ="btn"><%= link_to "Get Started", tutor_success_path %></button>
</div>
</div>

<%= link_to "Back", :back,  :class => "btn" %>

app/views/tutors/quizzes/french.html.erb
<script>
	function check(){

		var question1 = document.quiz.question1.value;
		var question2 = document.quiz.question2.value;
		var question3 = document.quiz.question3.value;
		var correct = 0;

		if (question1 == "Plus-que-parfait") {
			correct++;
		}
		if (question2 == "ent") {
			correct++;
		}
		if (question3 == "Faux") {
			correct++;
		}

		var messages = ["Great job!", "You need all 3 correct to become a tutor", "You need all 3 correct to become a tutor"];
		var score;


		if (correct == 0) {
			score = 2;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct > 0 && correct < 3) {
			score = 1;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct == 3) {
			score = 0;
			document.getElementById("start").style.visibility = "visible"
		}

		document.getElementById("after_submit").style.visibility = "visible";
  	document.getElementById("message").innerHTML = messages[score];
  	document.getElementById("number_correct").innerHTML = "You got " + correct + " correct.";
  }

</script>

<h2>I<%= t('.description') %> </h2>
<h2><%= t('.status') %> : <%= current_tutor.approval %></h2>

<div class="field">
<h1><%= t('.test') %> </h1>
<form id = "quiz" name = "quiz">


<p class = "questions">A quel temps est conjuguer le verbe dans la phrase: Nous étions partis à six heures du matin.</p>
<input type = "radio" id = "mc" name = "question1" value ="Imparfait"> Imparfait<br>
<input type = "radio" id = "mc" name = "question1" value ="Plus-que-parfait"> Plus-que-parfait<br>
<input type = "radio" id = "mc" name = "question1" value ="Passé composé"> Passé composé<br>

<p class = "questions">Compléter la terminaison: Mes freres et soeurs n'arret___ pas de m'embeter!</p>
<input id = "textbox" type = "text" name = "question2">

<p class = "questions">Avec un participe passé, l'auxiliaire "avoir" s'accorde toujours en genre et en nombre.</p>
<input type = "radio" id = "mc" name = "question3" value = "Vrai"> Vrai<br>
<input type = "radio" id = "mc" name = "question3" value = "Faux"> Faux<br>


<input id = "button" type = "button" value = "I'm finished!" onclick = "check();">

</form>

<div id = "after_submit">
<p id = "number_correct"></p>
<p id = "message"></p>
<button id = "refresh", class ="btn"><%= link_to "Refresh", "" %></button>
<button id = "start", class ="btn"><%= link_to "Get Started", tutor_success_path %></button>
</div>
</div>

<%= link_to "Back", :back,  :class => "btn" %>

app/views/tutors/quizzes/german.html.erb
<script>
	function check(){

		var question1 = document.quiz.question1.value;
		var question2 = document.quiz.question2.value;
		var question3 = document.quiz.question3.value;
		var correct = 0;

		if (question1 == "sie") {
			correct++;
		}
		if (question2 == "weil") {
			correct++;
		}
		if (question3 == "der alte Mann") {
			correct++;
		}

		var messages = ["Great job!", "You need all 3 correct to become a tutor", "You need all 3 correct to become a tutor"];
		var score;


		if (correct == 0) {
			score = 2;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct > 0 && correct < 3) {
			score = 1;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct == 3) {
			score = 0;
			document.getElementById("start").style.visibility = "visible"
		}

		document.getElementById("after_submit").style.visibility = "visible";
  	document.getElementById("message").innerHTML = messages[score];
  	document.getElementById("number_correct").innerHTML = "You got " + correct + " correct.";
  }

</script>

<h2><%= t('.description') %> </h2>
<h2><%= t('.status') %> : <%= current_tutor.approval %></h2>

<div class="field">
<h1><%= t('.test') %> </h1>
<form id = "quiz" name = "quiz">


<p class = "questions">Haben ___ lust, heute Abend fernhuzen? </p>
<input id = "textbox" type = "text" name = "question1">

<p class = "questions">Ich liebe Deutsch, ___ es toll ist.</p>
<input type = "radio" id = "mc" name = "question2" value = "weil"> weil<br>
<input type = "radio" id = "mc" name = "question2" value = "oder"> oder<br>

<p class = "questions">Beantworte das richtige Wort fur Nominativ:</p>
<input type = "radio" id = "mc" name = "question3" value = "der alte Mann"> der alte Mann<br>
<input type = "radio" id = "mc" name = "question3" value = "der altern Mann"> der altern Mann<br>


<input id = "button" type = "button" value = "I'm finished!" onclick = "check();">

</form>

<div id = "after_submit">
<p id = "number_correct"></p>
<p id = "message"></p>
<button id = "refresh", class ="btn"><%= link_to "Refresh", "" %></button>
<button id = "start", class ="btn"><%= link_to "Get Started", tutor_success_path %></button>
</div>
</div>


<%= link_to "Back", :back,  :class => "btn" %>

app/views/tutors/quizzes/spanish.html.erb
<script>
	function check(){

		var question1 = document.quiz.question1.value;
		var question2 = document.quiz.question2.value;
		var question3 = document.quiz.question3.value;
		var correct = 0;

		if (question1 == "17") {
			correct++;
		}
		if (question2 == "3") {
			correct++;
		}
		if (question3 == "A mí tampoco") {
			correct++;
		}

		var messages = ["Great job!", "You need all 3 correct to become a tutor", "You need all 3 correct to become a tutor"];
		var score;


		if (correct == 0) {
			score = 2;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct > 0 && correct < 3) {
			score = 1;
			document.getElementById("refresh").style.visibility = "visible"
		}

		if (correct == 3) {
			score = 0;
			document.getElementById("start").style.visibility = "visible"
		}

		document.getElementById("after_submit").style.visibility = "visible";
  	document.getElementById("message").innerHTML = messages[score];
  	document.getElementById("number_correct").innerHTML = "You got " + correct + " correct.";
  }

</script>

<h2><%= t('.description') %> </h2>
<h2><%= t('.status') %> : <%= current_tutor.approval %></h2>
<h1><%= t('.test') %> </h1>
<form id = "quiz" name = "quiz">


<p class = "questions">¿Cuantás comunidades autonomas tiene España? </p>
<input id = "textbox" type = "text" name = "question1">

<p class = "questions">¿Cuantos tiempos hay en español?</p>
<input type = "radio" id = "mc" name = "question2" value = "2"> 2<br>
<input type = "radio" id = "mc" name = "question2" value = "3"> 3<br>

<p class = "questions">No me gusta el fútbol.</p>

<input type = "radio" id = "mc" name = "question3" value = "A mí tampoco"> A mí tampoco<br>
<input type = "radio" id = "mc" name = "question3" value = "A mi tambien"> A mi tambien<br>


<input id = "button" class = "btn" type = "button" value = "I'm finished!" onclick = "check();">

</form>

<div id = "after_submit">
<p id = "number_correct"></p>
<p id = "message"></p>
<button id = "refresh", class ="btn"><%= link_to "Refresh", "" %></button>
<button id = "start", class ="btn"><%= link_to "Get Started", tutor_success_path %></button>
</div>


<%= link_to "Back", :back,  :class => "btn" %>

app/views/tutors/quizzes/tutortest.html.erb
<style>
.card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}
</style>

<h1><%= t('.description') %> </h1>
<h2><%= t('.description2') %> </h2>
<h2><%= t('.status') %>: <%= current_tutor.approval %></h2>

    <div class="card"><br/>
      <%= image_tag("spanish.png", size: "200x160") %>
      <div class="container">
        <h4><b><%= t('.spanish') %> </b></h4>
        <button class = "btn"><%= link_to "Spanish Test", tutor_spanish_test_path %></button>
      </div>
    </div>
    <div class="card"><br/>
      <%= image_tag("germany.jpg", size: "200x160") %>
      <div class="container">
        <h4><b><%= t('.german') %> </b></h4>
        <button class = "btn"><%= link_to "German Test", tutor_german_test_path %></button>
      </div>
    </div>
    <div class="card"><br/>
      <%= image_tag("french.png", size: "200x160") %>
      <div class="container">
        <h4><b><%= t('.french') %> </b></h4>
        <button class = "btn"><%= link_to "French Test", tutor_french_test_path %></button>
      </div>
    </div>
    <div class="card"><br/>
      <%= image_tag("english.png", size: "200x160") %>
      <div class="container">
        <h4><b><%= t('.english') %> </b></h4>
        <button class = "btn"><%= link_to "English Test", tutor_english_test_path %></button>
      </div>
    </div>